{{- range $name, $namespace := $.Values.namespaces }} 
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: {{ $name | quote}}
spec:
  limits:
  {{- if and $namespace $namespace.limit_range }}
    {{- $namespace.limit_range | toYaml | nindent 4 -}}
  {{ else }}
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "50m"
        memory: "128Mi"
  {{- end }}
{{- end }}